// Package commit0.v1 defines the versioned gRPC plugin contract for commit0-analyzer.
//
// # Version and Compatibility Policy
//
// This contract is "v0-PROVISIONAL": the wire format is versioned at the message level
// (ProtocolVersion in MetadataResponse), but the schema is NOT yet frozen. Breaking
// changes may happen between Phase 1 and Phase 2. Once Phase 2 confirms the transport
// (subprocess/gRPC over stdio), the contract is frozen at v0.
//
// Compatibility rule: the host accepts a plugin when host.Major == plugin.Major AND
// host.Minor >= plugin.Minor. A plugin with a higher Minor than the host is rejected
// (host may be missing optional fields the plugin depends on). Minor bumps are additive
// (new optional fields only). Major bumps are breaking.
//
// # SARIF Mapping Intent
//
// Fields are chosen to lower cleanly into a SARIF 2.1 `result` + `codeFlows`:
//   - Finding.id        → result.ruleId
//   - Finding.severity  → result.level (Critical/High→error, Medium→warning, Low→note)
//   - Finding.advisory  → result.relatedLocations or rule.help
//   - ReachabilityPath  → result.codeFlows[0].threadFlows[0].locations
//   - Location          → physicalLocation { artifactLocation.uri, region.startLine/startColumn }
//   - Finding with no ReachabilityPath MUST omit codeFlows (an empty codeFlows array
//     invalidates a SARIF document and causes GitHub code scanning to reject the whole upload).
//
// # Analyze Stream Direction and Framing
//
// The Analyze RPC is a server-streaming call: the client (host) sends one AnalyzeRequest
// and the server (plugin) streams zero or more Finding messages back, closing the stream
// when analysis is complete. There is no client-side flow control; the plugin is expected
// to emit findings eagerly as they are discovered. The stream ends normally on a clean
// close; any error terminates the stream and is surfaced to the host as a gRPC status.
// Plugins MUST NOT buffer all findings and send them in a batch; hosts MUST tolerate
// findings arriving in any order.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: commit0/v1/plugin.proto

package commit0v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analyzer_Metadata_FullMethodName = "/commit0.v1.Analyzer/Metadata"
	Analyzer_Analyze_FullMethodName  = "/commit0.v1.Analyzer/Analyze"
)

// AnalyzerClient is the client API for Analyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analyzer is the gRPC service every commit0-analyzer plugin must implement.
//
// Transport: subprocess + gRPC over stdio (hashicorp/go-plugin pattern).
// The host launches the plugin as a child process and communicates over its
// stdio streams. Plugins MUST NOT write to stdout except via gRPC framing.
//
// Handshake sequence:
//  1. Host sends Metadata(MetadataRequest) to retrieve the plugin's identity
//     and protocol_version.
//  2. Host checks compatibility using the compat rule (see file header).
//  3. If compatible, host sends Analyze(AnalyzeRequest) and streams findings.
//  4. On incompatibility, the host terminates the plugin process immediately.
type AnalyzerClient interface {
	// Metadata returns the plugin's identity and protocol version.
	// Called once per plugin startup as part of the handshake.
	Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Analyze streams Finding messages back to the host as they are discovered.
	// Stream direction: client (host) sends ONE AnalyzeRequest; server (plugin)
	// streams ZERO OR MORE Finding messages and closes the stream when done.
	// Findings MAY arrive in any order. The stream ends cleanly on EOF; any
	// error is surfaced as a gRPC status code (codes.Internal for engine errors,
	// codes.InvalidArgument for bad input).
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Finding], error)
}

type analyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerClient(cc grpc.ClientConnInterface) AnalyzerClient {
	return &analyzerClient{cc}
}

func (c *analyzerClient) Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, Analyzer_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Finding], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Analyzer_ServiceDesc.Streams[0], Analyzer_Analyze_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeRequest, Finding]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Analyzer_AnalyzeClient = grpc.ServerStreamingClient[Finding]

// AnalyzerServer is the server API for Analyzer service.
// All implementations must embed UnimplementedAnalyzerServer
// for forward compatibility.
//
// Analyzer is the gRPC service every commit0-analyzer plugin must implement.
//
// Transport: subprocess + gRPC over stdio (hashicorp/go-plugin pattern).
// The host launches the plugin as a child process and communicates over its
// stdio streams. Plugins MUST NOT write to stdout except via gRPC framing.
//
// Handshake sequence:
//  1. Host sends Metadata(MetadataRequest) to retrieve the plugin's identity
//     and protocol_version.
//  2. Host checks compatibility using the compat rule (see file header).
//  3. If compatible, host sends Analyze(AnalyzeRequest) and streams findings.
//  4. On incompatibility, the host terminates the plugin process immediately.
type AnalyzerServer interface {
	// Metadata returns the plugin's identity and protocol version.
	// Called once per plugin startup as part of the handshake.
	Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// Analyze streams Finding messages back to the host as they are discovered.
	// Stream direction: client (host) sends ONE AnalyzeRequest; server (plugin)
	// streams ZERO OR MORE Finding messages and closes the stream when done.
	// Findings MAY arrive in any order. The stream ends cleanly on EOF; any
	// error is surfaced as a gRPC status code (codes.Internal for engine errors,
	// codes.InvalidArgument for bad input).
	Analyze(*AnalyzeRequest, grpc.ServerStreamingServer[Finding]) error
	mustEmbedUnimplementedAnalyzerServer()
}

// UnimplementedAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerServer struct{}

func (UnimplementedAnalyzerServer) Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedAnalyzerServer) Analyze(*AnalyzeRequest, grpc.ServerStreamingServer[Finding]) error {
	return status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedAnalyzerServer) mustEmbedUnimplementedAnalyzerServer() {}
func (UnimplementedAnalyzerServer) testEmbeddedByValue()                  {}

// UnsafeAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerServer will
// result in compilation errors.
type UnsafeAnalyzerServer interface {
	mustEmbedUnimplementedAnalyzerServer()
}

func RegisterAnalyzerServer(s grpc.ServiceRegistrar, srv AnalyzerServer) {
	// If the following call panics, it indicates UnimplementedAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analyzer_ServiceDesc, srv)
}

func _Analyzer_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analyzer_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).Metadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_Analyze_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyzerServer).Analyze(m, &grpc.GenericServerStream[AnalyzeRequest, Finding]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Analyzer_AnalyzeServer = grpc.ServerStreamingServer[Finding]

// Analyzer_ServiceDesc is the grpc.ServiceDesc for Analyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commit0.v1.Analyzer",
	HandlerType: (*AnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metadata",
			Handler:    _Analyzer_Metadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Analyze",
			Handler:       _Analyzer_Analyze_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "commit0/v1/plugin.proto",
}
