package advisory

// cweNames is a bundled, static id→name table for the most frequently-referenced
// CWE weaknesses (the CWE Top 25 plus common advisory categories). It carries no
// network dependency. Names are taken verbatim from the public MITRE CWE list
// (https://cwe.mitre.org/data/, CC-licensed reference data).
//
// This table is intentionally a curated subset, not the full CWE corpus: an id
// absent here is still kept id-only by the enricher (CWEName returns ok=false),
// so absence never drops weakness context.
var cweNames = map[string]string{
	"CWE-20":   "Improper Input Validation",
	"CWE-22":   "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
	"CWE-23":   "Relative Path Traversal",
	"CWE-59":   "Improper Link Resolution Before File Access ('Link Following')",
	"CWE-77":   "Improper Neutralization of Special Elements used in a Command ('Command Injection')",
	"CWE-78":   "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
	"CWE-79":   "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
	"CWE-89":   "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
	"CWE-94":   "Improper Control of Generation of Code ('Code Injection')",
	"CWE-119":  "Improper Restriction of Operations within the Bounds of a Memory Buffer",
	"CWE-120":  "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')",
	"CWE-125":  "Out-of-bounds Read",
	"CWE-129":  "Improper Validation of Array Index",
	"CWE-190":  "Integer Overflow or Wraparound",
	"CWE-200":  "Exposure of Sensitive Information to an Unauthorized Actor",
	"CWE-209":  "Generation of Error Message Containing Sensitive Information",
	"CWE-250":  "Execution with Unnecessary Privileges",
	"CWE-269":  "Improper Privilege Management",
	"CWE-276":  "Incorrect Default Permissions",
	"CWE-287":  "Improper Authentication",
	"CWE-295":  "Improper Certificate Validation",
	"CWE-306":  "Missing Authentication for Critical Function",
	"CWE-311":  "Missing Encryption of Sensitive Data",
	"CWE-312":  "Cleartext Storage of Sensitive Information",
	"CWE-319":  "Cleartext Transmission of Sensitive Information",
	"CWE-326":  "Inadequate Encryption Strength",
	"CWE-327":  "Use of a Broken or Risky Cryptographic Algorithm",
	"CWE-330":  "Use of Insufficiently Random Values",
	"CWE-331":  "Insufficient Entropy",
	"CWE-352":  "Cross-Site Request Forgery (CSRF)",
	"CWE-362":  "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
	"CWE-367":  "Time-of-check Time-of-use (TOCTOU) Race Condition",
	"CWE-369":  "Divide By Zero",
	"CWE-377":  "Insecure Temporary File",
	"CWE-400":  "Uncontrolled Resource Consumption",
	"CWE-401":  "Missing Release of Memory after Effective Lifetime",
	"CWE-415":  "Double Free",
	"CWE-416":  "Use After Free",
	"CWE-426":  "Untrusted Search Path",
	"CWE-434":  "Unrestricted Upload of File with Dangerous Type",
	"CWE-444":  "Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')",
	"CWE-476":  "NULL Pointer Dereference",
	"CWE-502":  "Deserialization of Untrusted Data",
	"CWE-522":  "Insufficiently Protected Credentials",
	"CWE-523":  "Unprotected Transport of Credentials",
	"CWE-532":  "Insertion of Sensitive Information into Log File",
	"CWE-552":  "Files or Directories Accessible to External Parties",
	"CWE-601":  "URL Redirection to Untrusted Site ('Open Redirect')",
	"CWE-611":  "Improper Restriction of XML External Entity Reference",
	"CWE-613":  "Insufficient Session Expiration",
	"CWE-617":  "Reachable Assertion",
	"CWE-639":  "Authorization Bypass Through User-Controlled Key",
	"CWE-668":  "Exposure of Resource to Wrong Sphere",
	"CWE-770":  "Allocation of Resources Without Limits or Throttling",
	"CWE-787":  "Out-of-bounds Write",
	"CWE-798":  "Use of Hard-coded Credentials",
	"CWE-862":  "Missing Authorization",
	"CWE-863":  "Incorrect Authorization",
	"CWE-908":  "Use of Uninitialized Resource",
	"CWE-915":  "Improperly Controlled Modification of Dynamically-Determined Object Attributes",
	"CWE-918":  "Server-Side Request Forgery (SSRF)",
	"CWE-1021": "Improper Restriction of Rendered UI Layers or Frames",
	"CWE-1333": "Inefficient Regular Expression Complexity",
}
