/**
 * Tests for resolveDepSource — the offline analyzable dependency-source resolver.
 *
 * Fixture layout (generated by build-fixtures.mjs under testdata/projects/depsource-fixtures/):
 *   esm-source/        — exports["."] → ./dist/index.js (readable multi-line ESM)
 *   minified-dist/     — main → ./dist/bundle.js (single-line minified)
 *   types-only/        — no runtime entry, only .d.ts
 *   cjs-main/          — main → ./lib/index.js (readable CJS)
 *   exports-conditions/ — exports["."] with import/require conditions
 */

import { describe, it, expect } from "vitest";
import path from "node:path";
import { resolveDepSource } from "../../depsource/resolve-dep-source.js";

const fixtureRoot = path.resolve(
  import.meta.dirname,
  "../../../testdata/projects/depsource-fixtures/node_modules"
);

function pkgDir(name: string): string {
  return path.join(fixtureRoot, name);
}

// ── (a) ESM source package via exports map ────────────────────────────────────

describe("esm-source package", () => {
  it("resolves entryFile to the dist/index.js", () => {
    const result = resolveDepSource({
      name: "esm-source",
      version: "1.0.0",
      dir: pkgDir("esm-source"),
    });
    expect(result.entryFile).toBe(
      path.join(pkgDir("esm-source"), "dist", "index.js")
    );
  });

  it("classifies fidelity as source", () => {
    const result = resolveDepSource({
      name: "esm-source",
      version: "1.0.0",
      dir: pkgDir("esm-source"),
    });
    expect(result.fidelity).toBe("source");
  });

  it("returns correct package metadata", () => {
    const result = resolveDepSource({
      name: "esm-source",
      version: "1.0.0",
      dir: pkgDir("esm-source"),
    });
    expect(result.package).toBe("esm-source");
    expect(result.version).toBe("1.0.0");
    expect(result.dir).toBe(pkgDir("esm-source"));
  });
});

// ── (b) Minified single-line bundle ──────────────────────────────────────────

describe("minified-dist package", () => {
  it("resolves to the bundle entry file", () => {
    const result = resolveDepSource({
      name: "minified-dist",
      version: "2.0.0",
      dir: pkgDir("minified-dist"),
    });
    expect(result.entryFile).toBe(
      path.join(pkgDir("minified-dist"), "dist", "bundle.js")
    );
  });

  it("classifies fidelity as reduced", () => {
    const result = resolveDepSource({
      name: "minified-dist",
      version: "2.0.0",
      dir: pkgDir("minified-dist"),
    });
    expect(result.fidelity).toBe("reduced");
  });
});

// ── (c) Types-only package (no runtime entry) ─────────────────────────────────

describe("types-only package", () => {
  it("returns entryFile null", () => {
    const result = resolveDepSource({
      name: "types-only",
      version: "1.0.0",
      dir: pkgDir("types-only"),
    });
    expect(result.entryFile).toBeNull();
  });

  it("classifies fidelity as none", () => {
    const result = resolveDepSource({
      name: "types-only",
      version: "1.0.0",
      dir: pkgDir("types-only"),
    });
    expect(result.fidelity).toBe("none");
  });
});

// ── (d) CJS main-only package ────────────────────────────────────────────────

describe("cjs-main package", () => {
  it("resolves entryFile via main field", () => {
    const result = resolveDepSource({
      name: "cjs-main",
      version: "1.2.3",
      dir: pkgDir("cjs-main"),
    });
    expect(result.entryFile).toBe(
      path.join(pkgDir("cjs-main"), "lib", "index.js")
    );
  });

  it("classifies fidelity as source", () => {
    const result = resolveDepSource({
      name: "cjs-main",
      version: "1.2.3",
      dir: pkgDir("cjs-main"),
    });
    expect(result.fidelity).toBe("source");
  });
});

// ── (e) Exports map with import/require conditions ────────────────────────────

describe("exports-conditions package", () => {
  it("resolves the import condition entry (prefers import over require)", () => {
    const result = resolveDepSource({
      name: "exports-conditions",
      version: "3.0.0",
      dir: pkgDir("exports-conditions"),
    });
    // Should pick the import condition: ./esm/index.js
    expect(result.entryFile).toBe(
      path.join(pkgDir("exports-conditions"), "esm", "index.js")
    );
  });

  it("classifies fidelity as source", () => {
    const result = resolveDepSource({
      name: "exports-conditions",
      version: "3.0.0",
      dir: pkgDir("exports-conditions"),
    });
    expect(result.fidelity).toBe("source");
  });
});

// ── Missing dir (edge case) ───────────────────────────────────────────────────

describe("missing package dir", () => {
  it("returns entryFile null and fidelity none without throwing", () => {
    const result = resolveDepSource({
      name: "nonexistent",
      version: "0.0.0",
      dir: pkgDir("__nonexistent__"),
    });
    expect(result.entryFile).toBeNull();
    expect(result.fidelity).toBe("none");
  });
});
