// Package anst.v1 defines the versioned gRPC plugin contract for anst-analyzer.
//
// # Version and Compatibility Policy
//
// This contract is "v0-PROVISIONAL": the wire format is versioned at the message level
// (ProtocolVersion in MetadataResponse), but the schema is NOT yet frozen. Breaking
// changes may happen between Phase 1 and Phase 2. Once Phase 2 confirms the transport
// (subprocess/gRPC over stdio), the contract is frozen at v0.
//
// Compatibility rule: the host accepts a plugin when host.Major == plugin.Major AND
// host.Minor >= plugin.Minor. A plugin with a higher Minor than the host is rejected
// (host may be missing optional fields the plugin depends on). Minor bumps are additive
// (new optional fields only). Major bumps are breaking.
//
// # SARIF Mapping Intent
//
// Fields are chosen to lower cleanly into a SARIF 2.1 `result` + `codeFlows`:
//   - Finding.id        → result.ruleId
//   - Finding.severity  → result.level (Critical/High→error, Medium→warning, Low→note)
//   - Finding.advisory  → result.relatedLocations or rule.help
//   - ReachabilityPath  → result.codeFlows[0].threadFlows[0].locations
//   - Location          → physicalLocation { artifactLocation.uri, region.startLine/startColumn }
//   - Finding with no ReachabilityPath MUST omit codeFlows (an empty codeFlows array
//     invalidates a SARIF document and causes GitHub code scanning to reject the whole upload).
//
// # Analyze Stream Direction and Framing
//
// The Analyze RPC is a server-streaming call: the client (host) sends one AnalyzeRequest
// and the server (plugin) streams zero or more Finding messages back, closing the stream
// when analysis is complete. There is no client-side flow control; the plugin is expected
// to emit findings eagerly as they are discovered. The stream ends normally on a clean
// close; any error terminates the stream and is surfaced to the host as a gRPC status.
// Plugins MUST NOT buffer all findings and send them in a batch; hosts MUST tolerate
// findings arriving in any order.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anst/v1/plugin.proto

package anstv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Confidence describes how certain the analyzer is that a vulnerable symbol or
// package is actually reachable from an entry point.
//
// CRITICAL INVARIANT: unknown ≠ safe. A Finding with CONFIDENCE_UNKNOWN MUST be
// surfaced to the user; it MUST NOT be silently suppressed. Callers must treat
// unknown as "could not determine reachability" (e.g. reflection, dynamic
// dispatch, cgo, build-tag mismatch), NOT as "not reachable."
//
// The proto3 zero value is CONFIDENCE_UNKNOWN so that a freshly-deserialized or
// default-constructed Finding is conservative by default.
type Confidence int32

const (
	// CONFIDENCE_UNKNOWN is the zero/default value. Reachability could not be
	// determined (e.g. reflection, dynamic dispatch, incomplete build graph,
	// build-tag mismatch). This finding MUST be surfaced, never suppressed.
	Confidence_CONFIDENCE_UNKNOWN Confidence = 0
	// CONFIDENCE_NOT_REACHABLE means the analyzer found no call path from any
	// entry point to the vulnerable symbol/package. Only NOT_REACHABLE findings
	// may be suppressed by a policy gate.
	Confidence_CONFIDENCE_NOT_REACHABLE Confidence = 1
	// CONFIDENCE_PACKAGE_REACHABLE means the vulnerable package is imported and
	// reachable from an entry point, but the specific vulnerable symbol could not
	// be confirmed (symbol-level data unavailable or inconclusive).
	Confidence_CONFIDENCE_PACKAGE_REACHABLE Confidence = 2
	// CONFIDENCE_SYMBOL_REACHABLE means a concrete call-graph path from an entry
	// point to the specific vulnerable symbol was found. This is the highest
	// confidence tier; ReachabilityPath SHOULD be populated.
	Confidence_CONFIDENCE_SYMBOL_REACHABLE Confidence = 3
)

// Enum value maps for Confidence.
var (
	Confidence_name = map[int32]string{
		0: "CONFIDENCE_UNKNOWN",
		1: "CONFIDENCE_NOT_REACHABLE",
		2: "CONFIDENCE_PACKAGE_REACHABLE",
		3: "CONFIDENCE_SYMBOL_REACHABLE",
	}
	Confidence_value = map[string]int32{
		"CONFIDENCE_UNKNOWN":           0,
		"CONFIDENCE_NOT_REACHABLE":     1,
		"CONFIDENCE_PACKAGE_REACHABLE": 2,
		"CONFIDENCE_SYMBOL_REACHABLE":  3,
	}
)

func (x Confidence) Enum() *Confidence {
	p := new(Confidence)
	*p = x
	return p
}

func (x Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_anst_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Confidence) Type() protoreflect.EnumType {
	return &file_anst_v1_plugin_proto_enumTypes[0]
}

func (x Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confidence.Descriptor instead.
func (Confidence) EnumDescriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Severity classifies the impact of a vulnerability.
type Severity int32

const (
	// SEVERITY_UNSPECIFIED is the zero/default. Treat as unknown severity.
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_anst_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_anst_v1_plugin_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{1}
}

// Location identifies a source position.
// Maps to SARIF physicalLocation { artifactLocation.uri, region.startLine/startColumn }.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file is a path relative to the module root (e.g. "pkg/foo/bar.go").
	File          string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_anst_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Location) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// CallStep is one frame in a reachability call chain.
type CallStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// location is the call site (the line that calls the next step).
	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// symbol is the fully-qualified symbol at this call site (e.g. "pkg/foo.Bar").
	Symbol        string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStep) Reset() {
	*x = CallStep{}
	mi := &file_anst_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStep) ProtoMessage() {}

func (x *CallStep) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStep.ProtoReflect.Descriptor instead.
func (*CallStep) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CallStep) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CallStep) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// ReachabilityPath is a concrete call chain from an entry point to a vulnerable
// symbol. Maps to SARIF result.codeFlows[0].threadFlows[0].locations.
// Only populated when Confidence == CONFIDENCE_SYMBOL_REACHABLE.
type ReachabilityPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// steps is the ordered sequence of call frames, from entry point to
	// the vulnerable symbol (inclusive at both ends).
	Steps         []*CallStep `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReachabilityPath) Reset() {
	*x = ReachabilityPath{}
	mi := &file_anst_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityPath) ProtoMessage() {}

func (x *ReachabilityPath) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityPath.ProtoReflect.Descriptor instead.
func (*ReachabilityPath) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ReachabilityPath) GetSteps() []*CallStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// AdvisoryRef identifies the vulnerability this Finding relates to.
// Maps to SARIF result.ruleId + rule.help.
type AdvisoryRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the canonical advisory identifier (e.g. "GO-2024-0001", "CVE-2024-12345").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// url is a human-readable link to the advisory (optional).
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// aliases are alternative identifiers (e.g. CVEs when the primary id is a GHSA).
	Aliases       []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvisoryRef) Reset() {
	*x = AdvisoryRef{}
	mi := &file_anst_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisoryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisoryRef) ProtoMessage() {}

func (x *AdvisoryRef) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisoryRef.ProtoReflect.Descriptor instead.
func (*AdvisoryRef) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AdvisoryRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdvisoryRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdvisoryRef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Finding is the normalized output of a single vulnerability report from a plugin.
//
// SARIF lowering:
//   - id / advisory → result.ruleId + rule.help
//   - severity      → result.level
//   - path          → result.codeFlows (OMIT if nil/empty; empty codeFlows is invalid SARIF)
//   - properties    → result.properties (carries algorithm, snapshot_digest, goos, goarch, tags)
//   - pillar/lang   → reserved tags for multi-pillar expansion (SAST, Secrets, …)
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// advisory is the vulnerability reference this finding relates to.
	Advisory *AdvisoryRef `protobuf:"bytes,1,opt,name=advisory,proto3" json:"advisory,omitempty"`
	// module is the Go module path of the dependency containing the vulnerability
	// (e.g. "golang.org/x/net").
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// confidence is the analyzer's certainty about reachability.
	// The zero value is CONFIDENCE_UNKNOWN (conservative default).
	Confidence Confidence `protobuf:"varint,3,opt,name=confidence,proto3,enum=anst.v1.Confidence" json:"confidence,omitempty"`
	// severity is the vulnerability's impact classification.
	Severity Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=anst.v1.Severity" json:"severity,omitempty"`
	// path is the concrete call chain, if available.
	// MUST be nil/omitted when confidence < CONFIDENCE_SYMBOL_REACHABLE,
	// and MUST be populated when confidence == CONFIDENCE_SYMBOL_REACHABLE.
	Path *ReachabilityPath `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// properties carries analyzer metadata:
	//
	//	"goos"             → GOOS used for analysis
	//	"goarch"           → GOARCH used for analysis
	//	"tags"             → comma-separated build tags
	//	"snapshot_digest"  → hex digest of the advisory snapshot used
	//	"algorithm"        → call-graph algorithm (e.g. "vta", "rta", "cha")
	Properties map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pillar is a reserved tag for multi-pillar expansion (e.g. "sca", "sast", "secrets").
	// Populated by the host when aggregating findings from multiple plugin types.
	Pillar string `protobuf:"bytes,7,opt,name=pillar,proto3" json:"pillar,omitempty"`
	// language is a reserved tag for multi-language support (e.g. "go", "js", "python").
	Language      string `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_anst_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetAdvisory() *AdvisoryRef {
	if x != nil {
		return x.Advisory
	}
	return nil
}

func (x *Finding) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Finding) GetConfidence() Confidence {
	if x != nil {
		return x.Confidence
	}
	return Confidence_CONFIDENCE_UNKNOWN
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetPath() *ReachabilityPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Finding) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Finding) GetPillar() string {
	if x != nil {
		return x.Pillar
	}
	return ""
}

func (x *Finding) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Symbol identifies a specific function or method within a package.
type Symbol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// package is the fully-qualified Go package path (e.g. "crypto/tls").
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// name is the symbol name within the package (e.g. "Conn.Read").
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_anst_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Symbol) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Advisory carries a resolved vulnerability from the advisory service to the analyzer.
// The host (Phase 2) resolves advisories and embeds them in AnalyzeRequest; the
// standalone runner (Phase 4) constructs an identical AnalyzeRequest from the same
// source, so both paths share one request type with no divergent plumbing.
type Advisory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the canonical advisory identifier (e.g. "GO-2024-0001").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// module is the affected Go module path.
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// version_range is the affected version range in semver notation (e.g. "<1.2.3").
	VersionRange string `protobuf:"bytes,3,opt,name=version_range,json=versionRange,proto3" json:"version_range,omitempty"`
	// symbols are the specific vulnerable symbols, if known (Go vuln DB provides these).
	Symbols []*Symbol `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"`
	// symbol_level indicates whether symbol-level data is available for this advisory.
	// When false, the analyzer MUST degrade to CONFIDENCE_PACKAGE_REACHABLE at best.
	SymbolLevel bool `protobuf:"varint,5,opt,name=symbol_level,json=symbolLevel,proto3" json:"symbol_level,omitempty"`
	// sources lists the advisory data sources (e.g. ["go-vuln-db"]).
	Sources       []string `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advisory) Reset() {
	*x = Advisory{}
	mi := &file_anst_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advisory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advisory) ProtoMessage() {}

func (x *Advisory) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advisory.ProtoReflect.Descriptor instead.
func (*Advisory) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Advisory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Advisory) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Advisory) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

func (x *Advisory) GetSymbols() []*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Advisory) GetSymbolLevel() bool {
	if x != nil {
		return x.SymbolLevel
	}
	return false
}

func (x *Advisory) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

// BuildConfig specifies the build environment for analysis.
// When the analysis target cannot be built for the specified config, the analyzer
// MUST degrade to CONFIDENCE_UNKNOWN (never NOT_REACHABLE) for affected findings.
type BuildConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// goos is the target GOOS (e.g. "linux", "darwin", "windows").
	Goos string `protobuf:"bytes,1,opt,name=goos,proto3" json:"goos,omitempty"`
	// goarch is the target GOARCH (e.g. "amd64", "arm64").
	Goarch string `protobuf:"bytes,2,opt,name=goarch,proto3" json:"goarch,omitempty"`
	// tags are additional build tags to apply during analysis.
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildConfig) Reset() {
	*x = BuildConfig{}
	mi := &file_anst_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConfig) ProtoMessage() {}

func (x *BuildConfig) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConfig.ProtoReflect.Descriptor instead.
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *BuildConfig) GetGoos() string {
	if x != nil {
		return x.Goos
	}
	return ""
}

func (x *BuildConfig) GetGoarch() string {
	if x != nil {
		return x.Goarch
	}
	return ""
}

func (x *BuildConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// AnalyzeRequest is the single input type for the Analyze RPC.
// Used by both the plugin host (Phase 2) and the standalone runner (Phase 4);
// there is exactly one request type — no divergent advisory plumbing.
type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// module_root is the absolute path to the Go module root directory.
	ModuleRoot string `protobuf:"bytes,1,opt,name=module_root,json=moduleRoot,proto3" json:"module_root,omitempty"`
	// entrypoints are the packages to use as analysis roots (e.g. ["./cmd/myapp"]).
	// When empty, the analyzer auto-detects entry points based on the module type
	// (main packages → main+init+tests; library → exported symbols + init).
	Entrypoints []string `protobuf:"bytes,2,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	// build_config specifies the build environment for analysis.
	BuildConfig *BuildConfig `protobuf:"bytes,3,opt,name=build_config,json=buildConfig,proto3" json:"build_config,omitempty"`
	// advisories are the resolved vulnerabilities to check reachability for.
	Advisories    []*Advisory `protobuf:"bytes,4,rep,name=advisories,proto3" json:"advisories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_anst_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeRequest) GetModuleRoot() string {
	if x != nil {
		return x.ModuleRoot
	}
	return ""
}

func (x *AnalyzeRequest) GetEntrypoints() []string {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *AnalyzeRequest) GetBuildConfig() *BuildConfig {
	if x != nil {
		return x.BuildConfig
	}
	return nil
}

func (x *AnalyzeRequest) GetAdvisories() []*Advisory {
	if x != nil {
		return x.Advisories
	}
	return nil
}

// MetadataRequest is sent by the host to identify itself during the handshake.
type MetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_version is the host's protocol version string (e.g. "0.1").
	HostVersion   string `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_anst_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

// MetadataResponse is returned by a plugin to describe itself.
type MetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin's human-readable name (e.g. "go-reachability").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin's own semantic version (e.g. "0.1.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// protocol_version is the protocol version this plugin implements (e.g. "0.1").
	// The host uses this to decide compatibility before calling Analyze.
	ProtocolVersion string `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// description is a short human-readable description of what the plugin analyzes.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// supported_languages lists the programming language pillars this plugin handles.
	SupportedLanguages []string `protobuf:"bytes,5,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_anst_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anst_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_anst_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

var File_anst_v1_plugin_proto protoreflect.FileDescriptor

const file_anst_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x14anst/v1/plugin.proto\x12\aanst.v1\"J\n" +
	"\bLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"Q\n" +
	"\bCallStep\x12-\n" +
	"\blocation\x18\x01 \x01(\v2\x11.anst.v1.LocationR\blocation\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\";\n" +
	"\x10ReachabilityPath\x12'\n" +
	"\x05steps\x18\x01 \x03(\v2\x11.anst.v1.CallStepR\x05steps\"I\n" +
	"\vAdvisoryRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\"\x9b\x03\n" +
	"\aFinding\x120\n" +
	"\badvisory\x18\x01 \x01(\v2\x14.anst.v1.AdvisoryRefR\badvisory\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x123\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x0e2\x13.anst.v1.ConfidenceR\n" +
	"confidence\x12-\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x11.anst.v1.SeverityR\bseverity\x12-\n" +
	"\x04path\x18\x05 \x01(\v2\x19.anst.v1.ReachabilityPathR\x04path\x12@\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2 .anst.v1.Finding.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06pillar\x18\a \x01(\tR\x06pillar\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x06Symbol\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbf\x01\n" +
	"\bAdvisory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12#\n" +
	"\rversion_range\x18\x03 \x01(\tR\fversionRange\x12)\n" +
	"\asymbols\x18\x04 \x03(\v2\x0f.anst.v1.SymbolR\asymbols\x12!\n" +
	"\fsymbol_level\x18\x05 \x01(\bR\vsymbolLevel\x12\x18\n" +
	"\asources\x18\x06 \x03(\tR\asources\"M\n" +
	"\vBuildConfig\x12\x12\n" +
	"\x04goos\x18\x01 \x01(\tR\x04goos\x12\x16\n" +
	"\x06goarch\x18\x02 \x01(\tR\x06goarch\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\xbf\x01\n" +
	"\x0eAnalyzeRequest\x12\x1f\n" +
	"\vmodule_root\x18\x01 \x01(\tR\n" +
	"moduleRoot\x12 \n" +
	"\ventrypoints\x18\x02 \x03(\tR\ventrypoints\x127\n" +
	"\fbuild_config\x18\x03 \x01(\v2\x14.anst.v1.BuildConfigR\vbuildConfig\x121\n" +
	"\n" +
	"advisories\x18\x04 \x03(\v2\x11.anst.v1.AdvisoryR\n" +
	"advisories\"4\n" +
	"\x0fMetadataRequest\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\"\xbe\x01\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\x13supported_languages\x18\x05 \x03(\tR\x12supportedLanguages*\x85\x01\n" +
	"\n" +
	"Confidence\x12\x16\n" +
	"\x12CONFIDENCE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18CONFIDENCE_NOT_REACHABLE\x10\x01\x12 \n" +
	"\x1cCONFIDENCE_PACKAGE_REACHABLE\x10\x02\x12\x1f\n" +
	"\x1bCONFIDENCE_SYMBOL_REACHABLE\x10\x03*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x042\x83\x01\n" +
	"\bAnalyzer\x12?\n" +
	"\bMetadata\x12\x18.anst.v1.MetadataRequest\x1a\x19.anst.v1.MetadataResponse\x126\n" +
	"\aAnalyze\x12\x17.anst.v1.AnalyzeRequest\x1a\x10.anst.v1.Finding0\x01B:Z8github.com/ducthinh993/anst-analyzer/pkg/contract/anstv1b\x06proto3"

var (
	file_anst_v1_plugin_proto_rawDescOnce sync.Once
	file_anst_v1_plugin_proto_rawDescData []byte
)

func file_anst_v1_plugin_proto_rawDescGZIP() []byte {
	file_anst_v1_plugin_proto_rawDescOnce.Do(func() {
		file_anst_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anst_v1_plugin_proto_rawDesc), len(file_anst_v1_plugin_proto_rawDesc)))
	})
	return file_anst_v1_plugin_proto_rawDescData
}

var file_anst_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_anst_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_anst_v1_plugin_proto_goTypes = []any{
	(Confidence)(0),          // 0: anst.v1.Confidence
	(Severity)(0),            // 1: anst.v1.Severity
	(*Location)(nil),         // 2: anst.v1.Location
	(*CallStep)(nil),         // 3: anst.v1.CallStep
	(*ReachabilityPath)(nil), // 4: anst.v1.ReachabilityPath
	(*AdvisoryRef)(nil),      // 5: anst.v1.AdvisoryRef
	(*Finding)(nil),          // 6: anst.v1.Finding
	(*Symbol)(nil),           // 7: anst.v1.Symbol
	(*Advisory)(nil),         // 8: anst.v1.Advisory
	(*BuildConfig)(nil),      // 9: anst.v1.BuildConfig
	(*AnalyzeRequest)(nil),   // 10: anst.v1.AnalyzeRequest
	(*MetadataRequest)(nil),  // 11: anst.v1.MetadataRequest
	(*MetadataResponse)(nil), // 12: anst.v1.MetadataResponse
	nil,                      // 13: anst.v1.Finding.PropertiesEntry
}
var file_anst_v1_plugin_proto_depIdxs = []int32{
	2,  // 0: anst.v1.CallStep.location:type_name -> anst.v1.Location
	3,  // 1: anst.v1.ReachabilityPath.steps:type_name -> anst.v1.CallStep
	5,  // 2: anst.v1.Finding.advisory:type_name -> anst.v1.AdvisoryRef
	0,  // 3: anst.v1.Finding.confidence:type_name -> anst.v1.Confidence
	1,  // 4: anst.v1.Finding.severity:type_name -> anst.v1.Severity
	4,  // 5: anst.v1.Finding.path:type_name -> anst.v1.ReachabilityPath
	13, // 6: anst.v1.Finding.properties:type_name -> anst.v1.Finding.PropertiesEntry
	7,  // 7: anst.v1.Advisory.symbols:type_name -> anst.v1.Symbol
	9,  // 8: anst.v1.AnalyzeRequest.build_config:type_name -> anst.v1.BuildConfig
	8,  // 9: anst.v1.AnalyzeRequest.advisories:type_name -> anst.v1.Advisory
	11, // 10: anst.v1.Analyzer.Metadata:input_type -> anst.v1.MetadataRequest
	10, // 11: anst.v1.Analyzer.Analyze:input_type -> anst.v1.AnalyzeRequest
	12, // 12: anst.v1.Analyzer.Metadata:output_type -> anst.v1.MetadataResponse
	6,  // 13: anst.v1.Analyzer.Analyze:output_type -> anst.v1.Finding
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_anst_v1_plugin_proto_init() }
func file_anst_v1_plugin_proto_init() {
	if File_anst_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anst_v1_plugin_proto_rawDesc), len(file_anst_v1_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anst_v1_plugin_proto_goTypes,
		DependencyIndexes: file_anst_v1_plugin_proto_depIdxs,
		EnumInfos:         file_anst_v1_plugin_proto_enumTypes,
		MessageInfos:      file_anst_v1_plugin_proto_msgTypes,
	}.Build()
	File_anst_v1_plugin_proto = out.File
	file_anst_v1_plugin_proto_goTypes = nil
	file_anst_v1_plugin_proto_depIdxs = nil
}
